# Generated by Django 2.1.1 on 2019-04-25 18:53

from django.conf import settings
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='House',
            fields=[
                ('identifier', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('house_name', models.CharField(db_index=True, max_length=255, unique=True)),
                ('rate', models.FloatField(blank=True)),
                ('is_occupied', models.BooleanField(default=False)),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('owner_id', models.ForeignKey(on_delete='CASCADE', related_name='landlord', to=settings.AUTH_USER_MODEL)),
                ('tenant_id', models.ForeignKey(on_delete='CASCADE', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
